# Generated by Django 3.2.4 on 2021-06-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='Comment',
        ),
    ]
