# Generated by Django 3.2.4 on 2021-06-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_body_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
    ]
