# Generated by Django 3.2.4 on 2021-07-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20210718_0014'),
    ]

    operations = [
        #migrations.CreateModel(
         #   name='Image',
          #  fields=[
           #     ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            #    ('image', models.ImageField(blank=True, null=True, upload_to='uploads/post_photos')),
            #],
        #),
        #migrations.AddField(
         #   model_name='post',
          #  name='image',
           # field=models.ManyToManyField(blank=True, to='social.Image'),
        #),
    ]
